.gitignore, examples/load-test-websockets.toml, examples/load-test.toml, examples/run.sh, go.mod, pkg/loadtest/clients/clients.go, pkg/loadtest/clients/http.go, pkg/loadtest/clients/websockets.go, pkg/loadtest/integration_test.go, pkg/loadtest/main_test.go, pkg/loadtest/runners.go, pkg/loadtest/slave.go
In addition to HTTP requests via the RPC, we need to be able to stress test a Tendermint network via the WebSockets endpoints. This PR adds support for a WebSockets load testing client `KVStoreWebSocketsClientType`.
=> Add support for WebSockets

README.md, examples/README.md, examples/load-test-autodetect-peers.toml, examples/load-test-websockets.toml, examples/load-test.toml, pkg/loadtest/clients/clients.go, pkg/loadtest/clients/http.go, pkg/loadtest/clients/websockets.go, pkg/loadtest/config.go, pkg/loadtest/http.go, pkg/loadtest/master.go, pkg/loadtest/models.go, pkg/loadtest/slave.go
This adds the necessary functionality for the master to poll a Tendermint seed node for new peers until a minimum number of peers is found before allowing slaves to connect. Once all necessary peers are found, slaves will be accepted and will be given a list of target nodes to use during testing.
=> Add ability to poll seed node for peers

CHANGELOG.md, pkg/loadtest/integration_test.go, pkg/loadtest/master.go, pkg/loadtest/slave.go
We need to be able to run load tests for a specific period of time without a limit on the number of transactions during that time period. This PR enables this functionality.
=> Add feature to allow for unlimited transactions, but limited time

CHANGELOG.md, examples/load-test-autodetect-peers.toml, examples/load-test-websockets.toml, examples/load-test.toml, go.mod, pkg/loadtest/clients/websockets.go, pkg/loadtest/config.go, pkg/loadtest/http.go, pkg/loadtest/integration_test.go, pkg/loadtest/master.go, pkg/loadtest/slave.go
This PR adds basic HTTP authentication to the master/slave interaction. It uses bcrypt-based hashes to validate the password supplied by the slave. Operating this over TLS should provide additional security in the master/slave interaction.
=> Add basic HTTP authentication

CHANGELOG.md, Makefile, cmd/tm-outage-sim-server/README.md, cmd/tm-outage-sim-server/main.go, internal/outagesim/http_interface.go, internal/outagesim/http_interface_test.go
This enhances the security of the `tm-outage-sim-server` utility, which allows us to bring a Tendermint node up/down through simple (now authenticated) POST requests.
=> Add basic HTTP authentication to tm-outage-sim-server

CHANGELOG.md, README.md, examples/load-test-autodetect-peers.toml, examples/load-test-websockets.toml, examples/load-test.toml, pkg/loadtest/config.go, pkg/loadtest/integration_test.go, pkg/loadtest/master.go, pkg/loadtest/outagesim.go, pkg/loadtest/outagesim_test.go
This PR aims to introduce support for the outage simulator into the load testing tool, such that, while a load test is underway, the master load testing node can turn Tendermint network nodes on and off according to a predefined schedule.
=> Add outage simulator support to load testing tool

CHANGELOG.md, examples/load-test-outage-sim.toml, pkg/loadtest/config.go, pkg/loadtest/master.go
This PR adds an example configuration file for outage simulation during load testing. It also fixes one or two minor issues relating to the outage simulator's configuration.
=> Add example config for outage simulator

cmd/tm-load-test/main.go, go.mod, pkg/loadtest/cli.go, pkg/loadtest/config.go, pkg/loadtest/integration_test.go, pkg/loadtest/main_test.go, pkg/loadtest/master.go, pkg/loadtest/remote_slave.go, pkg/loadtest/slave.go, pkg/loadtest/transactor_group.go, pkg/loadtest/websockets.go
This adds a `/metrics` endpoint to the master's web server that exposes per-slave and aggregated statistics and statuses in Prometheus' plain text format.
=> Add support for Prometheus metrics in master/slave mode

pkg/loadtest/cli.go, pkg/loadtest/config.go, pkg/loadtest/integration_test.go, pkg/loadtest/loadtest.go, pkg/loadtest/master.go, pkg/loadtest/tm_network_info.go
This commit allows for a broader endpoint selection strategy for load testing. Specifically, there are 3 possible strategies for selecting endpoints for load testing:
1. "supplied" - use only supplied endpoints for load testing.
2. "discovered" - use only discovered endpoints for load testing (and none of the supplied ones).
3. "any" - use both supplied and discovered endpoints for testing.
This allows for permutations such as when one supplies a seed node as an endpoint, but one does not want to submit transactions to that seed node.
This necessarily introduces another command line parameter `--max-endpoints`, which allows one to restrict the maximum number of endpoints returned for load testing after applying the selection
strategy.
=> Expand on endpoint selection strategy

pkg/loadtest/cli.go, pkg/loadtest/config.go, pkg/loadtest/loadtest.go, pkg/loadtest/master.go, pkg/loadtest/tm_network_info.go
As per discussions, we need to be able to instruct `tm-load-test` to wait until a minimum degree of P2P connectivity is reached (i.e. the minimum number of peers of which any given peer knows).
This commit introduces this functionality through a `--min-peer-connectivity` command line switch.
=> Add ability to wait for minimum connectivity

pkg/loadtest/cli.go, pkg/loadtest/master.go
The shutdown wait functionality was not working correctly and one couldn't cancel it previously, but now this commit fixes that.
=> Fix shutdown wait functionality

CHANGELOG.md, pkg/loadtest/cli.go, pkg/loadtest/master.go
Right now the periodically reported average tx throughput rate calculation is broken because I forgot to track the previous total number of txs. This PR fixes that, and bumps the minor version for `tm-load-test`.
=> Fix tx average rate calculation

CHANGELOG.md, README.md, pkg/loadtest/cli.go, pkg/loadtest/config.go, pkg/loadtest/master.go
Addresses #41 
A gauge called `tmloadtest_master_test_underway` is added here, whose default value is **-1**.
When the load test is underway, its value changes to whatever `--load-test-id` is configured to (default = 0). When the load test finishes or fails, its value is changed back to **-1**.
=> Expose load test ID Prometheus gauge

CHANGELOG.md, Makefile, README.md, pkg/loadtest/README.md, pkg/loadtest/cli.go, pkg/loadtest/client.go, pkg/loadtest/client_kvstore.go, pkg/loadtest/client_kvstore_test.go, pkg/loadtest/config.go, pkg/loadtest/integration_test.go, pkg/loadtest/master.go, pkg/loadtest/messages.go, pkg/loadtest/slave.go, pkg/loadtest/stats.go, pkg/loadtest/tm_network_info.go, pkg/loadtest/transactor.go, pkg/loadtest/transactor_group.go
Fixes #46 
Also introduces some new Prometheus metrics and aggregate stats that track overall transaction throughput and throughput rate in bytes and bytes/sec (respectively). This aids with testing and integration testing of this improvement.
=> Fix KVStore client transaction size

README.md, pkg/loadtest/transactor.go
Fixes two links to Tendermint v0.32 (the original version of Tendermint used to create this tool). The links still provide useful context, even though that version's no longer officially supported.
=> Fix links to GitHub to the specific version of Tendermint

.github/workflows/govulncheck.yml, Makefile
Adds a `vulncheck` Makefile target and CI workflow to run it.
=> ci: Add govulncheck

go.mod, go.sum
Temporarily replace the Tendermint Core dependency in tm-load-test with the Informal Systems fork.
=> Replace Tendermint Core dependency with Informal Systems fork

README.md, pkg/loadtest/integration_test.go, test/integration-test.sh
Minor improvements after merging #168.
It appears as though the integration test was running non-deterministically. One hypothesis I have about why is that it was attempting to execute the load test prior to the network being fully connected, resulting in no transactions being sent. This increases the minimum connectivity requirements before the load tests begin in the integration tests.
=> Integration test improvements

CHANGELOG.md, go.mod, pkg/loadtest/cli.go, pkg/loadtest/integration_test.go, pkg/loadtest/loadtest.go, pkg/loadtest/rpc_test.go, pkg/loadtest/tm_network_info.go, pkg/loadtest/transactor_group.go
Readies the v1.3.0 release that removes its Go dependency on Tendermint Core.
=> Prepare for v1.3.0

.github/workflows/govulncheck.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, go.mod
Go 1.18 is EOL and no longer supported.
=> Bump minimum Go version to 1.19

.github/workflows/govulncheck.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, go.mod
Fixes govulncheck failure in CI.
=> Bump Go version to 1.20

.github/workflows/govulncheck.yml, .github/workflows/lint.yml, Makefile
Updates govulncheck to use the latest patch release of Go, and the latest version of golangci-lint.
A bunch of the other Dependabot updates are failing because this uses a hard-coded version of Go in the govulncheck workflow in CI.
=> ci: Update govulncheck and linter

.github/workflows/govulncheck.yml, .github/workflows/release.yml, .github/workflows/test.yml
Update CI to always attempt to use the latest versions of Go.
=> ci: Use latest version of Go

go.mod, go.sum, pkg/loadtest/worker.go
It's essentially a drop-in replacement. 
with google/uuid, uuid.New() produces a v4 uuid by default, so produces the same behavior.
this is the relevant CVE: https://pkg.go.dev/vuln/GO-2022-0244
=> Replace vulnerable satori/go.uuid with google/uuid
